# Generated by Django 3.0.2 on 2020-04-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_integrante', models.IntegerField(verbose_name='codigo integrante')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('integrante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixture.Integrante')),
                ('fecha_debut', models.DateField(verbose_name='Fecha Debut')),
                ('cant_goles', models.IntegerField(default=0, verbose_name='Cantidad de Goles')),
            ],
            bases=('fixture.integrante',),
        ),
    ]
