# Generated by Django 2.2.2 on 2020-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_integrante', models.IntegerField(verbose_name='codigo integrante')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(auto_now_add=True, verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
