# Generated by Django 2.2.2 on 2020-01-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('integrante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixture.Integrante')),
                ('cant_goles', models.IntegerField(default=0, verbose_name='Goles')),
                ('fecha_debut', models.DateField(blank=True, null=True, verbose_name='Fecha de debut')),
            ],
            bases=('fixture.integrante',),
        ),
    ]
