# Generated by Django 3.0.2 on 2020-05-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='nombre',
            field=models.CharField(default='N-N', max_length=50, verbose_name='Nombre'),
        ),
    ]
