# Generated by Django 2.2.2 on 2020-01-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='cant_goles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles'),
        ),
    ]
