# Generated by Django 3.0.2 on 2020-05-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_auto_20200509_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Posición'),
        ),
    ]
