# Generated by Django 2.2.2 on 2020-01-22 17:41

from django.db import migrations, models
import django.db.models.deletion
import fixture.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_auto_20200122_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='DT',
            fields=[
                ('integrante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixture.Integrante')),
                ('anios_experiencia', models.IntegerField(default=0, null=True, verbose_name='Años de Experiencia')),
                ('nacionalidad', models.ForeignKey(on_delete=fixture.models.Nacionalidad, to='fixture.Nacionalidad')),
            ],
            bases=('fixture.integrante',),
        ),
    ]
