# Generated by Django 2.2.2 on 2020-01-23 19:40

from django.db import migrations, models
import fixture.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_dt_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=2, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Posicion')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50, verbose_name='Equipo')),
                ('grupo', models.ForeignKey(on_delete=fixture.models.Grupo, to='fixture.Grupo')),
            ],
        ),
    ]
